pykickstart/pykickstart

- pykickstart.spec
- pykickstart/load.py
- pykickstart/parser.py
- pykickstart/version.py
- tools/ksvalidator
Because urlgrabber is being dropped by many significant software projects in
Fedora, Pykickstart can't keep depending on it once it is converted to Python 3
(rhbz#985310).
This commit replaces the dep with requests with SSL verification turned on by
default. This could pose trouble in Python 2 if proper underlying packages
aren't installed [1]. In case this becomes a problem, the SSL_VERIFY constant
in constants.py may be switched to False.
[1] https://github.com/kennethreitz/requests/issues/749#issuecomment-19187417
> Replaced URLGrabber with requests (rhbz#1141245)

- pykickstart/commands/method.py
Python 3's ``copy.copy()`` works in a different way and hits more issues caused by
attributes accessed in the ``__getattr__`` override/redefinition. Long story short,
``copy.copy()`` creates a new empty object without calling ``__init__``  which it then
tries to populate with stuff from the copied object and as part of that calls
``hasattr()`` which in Python 3 no longer catches infinite recursion errors. The
solution is to raise ``AttributeError`` for all attributes defined in ``__init__`` that
are accessed from the ``__getattr__`` method override.
See http://nedbatchelder.com/blog/201010/surprising_getattr_recursion.html for
more information. Also kudos to bkabrda for nailing this down!
> Python 3 compatibility issues fixes

- pykickstart/commands/timezone.py
- pykickstart/handlers/f23.py
- tests/commands/timezone.py
NTP pools are entered by users as using the same NTP server URL multiple times
so we need to store the NTP server URLs in a list not in a set.
> Adapt the Timezone class to support NTP pools

- tests/commands/eula.py
Makes Python coverage happy with 100% test coverage.
> Cover corner case in commands/eula.py test

- po/Makefile
- pykickstart.spec
The .mo files in python3-kickstart are being installed to /usr/lib/python2.7/site-packages, which I don't think is what you want.
> Install the python3 .mo files to python3_sitelib

- pykickstart/version.py
- tests/baseclass.py
I hit a traceback about `found` being undefined or similar when I tried to run the test suite with a syntax error in my new code.
> Avoid traceback in module loading failure paths.

- pykickstart/commands/liveimg.py
The other object may be None, test for that first before trying to
access potentially non-existant attributes on it.
> Fix liveimg equality check

- pykickstart/parser.py
- pykickstart/sections.py
- tests/parser/packages.py
For a kickstart with `%package --instLangs=` set packages.instLangs to "" instead of None.
> Empty instLangs

- docs/kickstart-docs.rst
Add a description of the reqpart command to kickstart-docs.rst.
The command was implemented in rhbz#1164660.
> Add reqpart to docs

- docs/kickstart-docs.rst
The docs cover `--activate`, but the option isn't included in the
table itself, so if someone visually scans for it they might miss it.
I think this is a bit clearer.
I was looking for `--activate` docs while trying to debug
an Anaconda issue.
> docs: Add `--activate` as an explicit network option to the list

- pykickstart/commands/network.py
- pykickstart/handlers/f24.py
- tests/commands/network.py
If we specify a ipv6 only network configuration we still get bootproto=dhcp set,
which during kickstart makes networkmanager try to do a ipv4 dhcp which takes a
while to timeout.  We don't want bootproto=dhcp set when we specify --noipv4, so
make sure it gets zero'ed out when we see that command.
This is the V2 version that changes f24 and onwards.
> pykickstart: don't set bootProto if --noipv4

- docs/kickstart-docs.rst
Signed-off-by: Sol Jerome <sol@resolvity.com>
> docs/kickstart-docs.rst: iscrypted has no argument

- pykickstart/load.py
- tests/parser/handle_unicode.py
If the environment wasn't properly setup (eg. LANG set) then reading a
kickstart with unicode characters would fail. This adds a test to
simulate this, and switches to reading in binary mode and then decoding
to prevent tracebacks.
> Read kickstart files in binary, decode to utf-8

- pykickstart/load.py
- tests/parser/handle_unicode.py
The unicode kickstart problem only happens with py3, so conditionalize
_load_file to only decode it when running with py3.
> Only decode as utf-8 when using py3

- pykickstart/commands/volgroup.py
- pykickstart/handlers/rhel6.py
- tests/commands/volgroup.py
https://github.com/rhinstaller/pykickstart/blob/master/pykickstart/commands/volgroup.py#L174
`RHEL6_VolGroup` should inherit from `FC16_VolGroup` so that it understands disk reservation.
> Fix class inheritance in RHEL6_VolGroup

- .gitignore
- MANIFEST.in
- Makefile
- po/Makefile
- pykickstart/commands/device.py
- pykickstart/commands/dmraid.py
- pykickstart/commands/logvol.py
- pykickstart/commands/network.py
- pykickstart/commands/upgrade.py
- tests/pylint/runpylint.py
- tools/ksflatten
- tools/ksvalidator
- tools/ksverdiff
- translation-canary/.gitignore
- translation-canary/Makefile
- translation-canary/README.rst
- translation-canary/tests/pylint/runpylint.py
- translation-canary/tests/unittests/test_translatable.py
- translation-canary/tests/unittests/test_translated.py
- translation-canary/translation_canary/translatable/__init__.py
- translation-canary/translation_canary/translatable/__main__.py
- translation-canary/translation_canary/translatable/test_comment.py
- translation-canary/translation_canary/translatable/test_markup.py
- translation-canary/translation_canary/translated/__init__.py
- translation-canary/translation_canary/translated/__main__.py
- translation-canary/translation_canary/translated/test_markup.py
- translation-canary/translation_canary/translated/test_percentage.py
- translation-canary/translation_canary/translated/test_usability.py
- translation-canary/xgettext_werror.sh
I used --squash with the subtree add this time, so there's just one translation-canary commit (plus a merge) instead of all of them. I think I like that better and if no one disagrees I'll redo the other translation tests that before merging.
I did not modify the setup.py sdist command for this one since I realized while doing so that pykickstart needs to care about python2, and translation-canary is only python3. So I guess this is the model I'll be using for other setup.py projects.
A handful of format string problems, and lt.po has the same Plural-Forms error that blivet had ("or" instead of "||")
> Translation tests

- tests/baseclass.py
- tests/parser/include.py
> Use six.assertRaisesRegex to keep the tests working in python2.

- Makefile
- pykickstart/base.py
- pykickstart/commands/keyboard.py
- pykickstart/commands/reqpart.py
- pykickstart/handlers/control.py
- pykickstart/options.py
- pykickstart/orderedset.py
- pykickstart/parser.py
- pykickstart/version.py
Add static typing information to the public methods on pykickstart.base
and pykickstart.version, since that seems like as good a place as any to
start, and any of the collection types where mypy needs type
annotations. Run mypy during 'make test' and add enough 'type: ignore'
comments to make it work.
All of the type information is specified as comments instead of using
the Python 3 type annotation syntax because pykickstart needs to be able
run as Python 2. The type comments are kind of gross in that they need
to be crammed all on to one line, but they seem a lot less likely to
make everything explode than the mypy codec provided as an alternative.
Fixed one actual type problem: pykickstart.base.BaseHandler initializes
currentLine as an int, but everywhere else this value is a string. …
> Add some initial static typing information to pykickstart.

- tests/load.py
By default, the python http server will print the httpd logs to stderr.
In our usage, those messages include inducing an error by feeding a
bunch of HTTPS data in as a HTTP request. This is ugly. Just skip the
logging entirely because who cares.
> Do not log httpd messages in the load tests.

- pykickstart/version.py
- tests/baseclass.py
- tests/version.py
Instead of choosing between two deprecated modules, use the one that is
in both Python 2.7 and Python 3.2+
> Use importlib to import modules.

- docs/kickstart-docs.rst
It appears that GitHub's reStructuredText processor doesn't like links within emboldened text. Sorry about that.
> Add DNF system-upgrade near FedUp references

- tests/tools/ksvalidator.py
- tests/tools/tooltest.py
- tools/ksvalidator.py
Added test coverage for ksvalidator (+classes to be used also for other tools) + fixed a rather 'cosmetic' issue in ksvalidator (kickstart filename as a positional argument was required even with -l/--listversions option).
> Pykickstart tools tests

- docs/kickstart-docs.rst
- pykickstart/parser.py
- pykickstart/sections.py
- tests/packages.py
This allows minimal installs, and reproducible ones, by not including
weak dependencies.
From https://bugzilla.redhat.com/show_bug.cgi?id=1331100
> Add support for --excludeWeakdeps option to %packages.

- Makefile
- pykickstart/base.py
- pykickstart/base.pyi
- pykickstart/handlers/control.pyi
- pykickstart/parser.py
- pykickstart/parser.pyi
- pykickstart/sections.py
- pykickstart/sections.pyi
- pykickstart/version.py
- pykickstart/version.pyi
- setup.py
mypy's --use-python-path option has been removed, since the results were
often misleading. Move the existing type comments into .pyi stub files,
which are installed to /usr/lib/python*/site-packages, and run the type
checks based on those.
The test for this is probably going to fail since I haven't actually built this new mypy yet.
> Adapt to the new version of mypy

- .travis.yml
- Makefile
- setup.py
- tests/pylint/runpylint.py
- tools/ksflatten.py
- tools/ksshell.py
- tools/ksvalidator.py
- tools/ksverdiff.py
- translation-canary/tests/pylint/runpylint.py
The only drawback I'm currently seeing is that multiprocessing and coverage don't play well in Travis. I frequently get some JSON errors or timeouts, see https://travis-ci.org/atodorov/pykickstart/builds/141046781.
However I've seen the same thing locally and I also think there's something wrong with the coverage generation from nose. The tools tests for example execute a subprocess with "coverage run ..." instead of relying on nose. I'll take a look at this in another PR. Maybe we'll want to disable multiprocessing for now, what do you think ?
> Enable Travis-CI

- pykickstart/commands/autopart.py
- pykickstart/commands/bootloader.py
- pykickstart/commands/btrfs.py
- pykickstart/commands/driverdisk.py
- pykickstart/commands/ignoredisk.py
- pykickstart/commands/iscsi.py
- pykickstart/commands/logvol.py
- pykickstart/commands/method.py
- pykickstart/commands/ostreesetup.py
- pykickstart/commands/partition.py
- pykickstart/commands/raid.py
- pykickstart/commands/repo.py
- pykickstart/commands/reqpart.py
- pykickstart/commands/url.py
- pykickstart/commands/volgroup.py
- pykickstart/commands/zfcp.py
- tests/commands/__init__.py
This is related to my previous comment at https://github.com/rhinstaller/pykickstart/pull/91#discussion-diff-69723629. Let's try to avoid the case where the definition looks like
RHEL7_AutoPart = F21_AutoPart
b/c this can interfere with the commandMap handler test and allow the introduction of unwanted bugs. NOTE: these classes don't really do anything. we can either remove them and update the handler maps or properly inherit them from whatever is on the right hand side so that the handlers commandMap test has a better chance of detecting possible errors. The current list of offences is
```
ERROR: In `commands/autopart.py` RHEL7_AutoPart = F21_AutoPart
ERROR: In `commands/volgroup.py` RHEL7_VolGroup = F21_VolGroup
ERROR: In `commands/method.py` F14_Method = FC3_Method
ERROR: In …
```
> Test how command and data classes are defined

- docs/kickstart-docs.rst
- pykickstart/commands/timezone.py
- pykickstart/handlers/f25.py
- pykickstart/handlers/rhel7.py
- tests/commands/timezone.py
This adds a separate RHEL7 & F25 version of the modified timezone command & the corresponding tests, as suggested in:
https://github.com/rhinstaller/pykickstart/pull/87#issuecomment-225897780
> Pykickstart 2 version of the timezone-without-arguments patch

- docs/kickstart-docs.rst
- pykickstart/commands/timezone.py
- pykickstart/handlers/f25.py
- pykickstart/handlers/rhel7.py
- tests/commands/timezone.py
This adds a separate RHEL7 & F25 version of the modified timezone command & the corresponding tests, as suggested in:
https://github.com/rhinstaller/pykickstart/pull/87#issuecomment-225897780
> Master version of the timezone-without-arguments patch

- pykickstart/commands/timezone.py
The `F23_Timezone` is required because of ntp pools. NTP pools are now specified with repeating of the same ntp server 4 times.
The problem here is that in `F18_Timezone` there is `set()` for storing ntp_servers which can't store multiple times the same server. The variable was changed to `list()` in `F23_Timezone`.
> Fix timezone subclassing

- tests/commands/network.py
follow-up of https://github.com/rhinstaller/pykickstart/pull/101
> replace assertEquals with assertEqual in network tests

- pykickstart/options.py
the underlying problem is in ArgumentParser.__init_ and its
deprecated version argument which was resetting self.version to
None.
@clumens this makes all tests run again under both Python 3 and Python 2.
> Fix Python 2 builds by assigning to KSOptionParser.version properly

- tests/commands/__init__.py
@clumens I've temporarily disabled this test case. I will also go ahead and file issues for each individual module so we don't forget to finally update the descriptions.
Note: on my system I wasn't able to reproduce the failures. I think this has to do with how mock finds the imported modules where it needs to apply the patch. With the current changes I'm able to generate the list of errors as expected. Let me know how that works for you.
> Disable HelpAndDescription_TestCase

- docs/kickstart-docs.rst
- pykickstart/commands/displaymode.py
- pykickstart/constants.py
- pykickstart/handlers/__init__.py
- pykickstart/handlers/f26.py
- pykickstart/version.py
- tests/commands/displaymode.py
- tests/version.py
To prevent kickstart tests timeouts I need to add non-interactive mode which will kill installation instead of waiting on user interaction.
Anaconda patch will follow after the `anaconda.py` PR will be merged.
> Py2 add noninteractive

- pykickstart/parser.py
When errors are printed to `stdout` instead of `stderr` then Dracut takes this Pykickstart errors as output from parse-kickstart script.
> Print errors to stderr when errors aren't fatal

- pykickstart/commands/displaymode.py
This is already in `FC3_DisplayMode` class so there is no need to have this in `F26_DisplayMode` class.
Introduced in PR https://github.com/rhinstaller/pykickstart/pull/111 . As far as I understand this, it shouldn't be used twice in the same command.
> Remove duplicated kwargs.get displayMode variable

- pykickstart/commands/rootpw.py
Closes #119 
Also for the `sshpw` part note that the documentation says:
```
---sshkey 
If this is used then the <password> string is interpreted as an ssh key value.
```
which also means we can have a space character. Indeed there is also a test for that:
```
self.assert_parse("sshpw --username=someguy --sshkey a ssh key with spaces", "sshpw --username=someguy --sshkey a ssh key with spaces\n")
```
It is unfortunate that the `<password>` argument is rendered as `[password [password ...]]` in the docs but that is a minor inconvenience given that the behavior is fully documented otherwise.
@Frodox, @clumens @jkonecny12. I propose to merge this one in favor of #119. Please review.
> rootpw: document that password isn't required with --lock

- docs/kickstart-docs.rst
This caught us when trying to have our Vagrant box inherit from the
OpenStack/cloud one and both having a `services` section.
> docs: Note under %include that most sections don't do merging

- Makefile
Now builds are failing because `coverage combine` doesn't work on Rawhide. It would be nice to find why this is happening but so or so this is not a reason for build to fail.
> Ignore errors from coverage tests

- docs/kickstart-docs.rst
- pykickstart/commands/autopart.py
- tests/commands/autopart.py
A /home partition will not be created with --nohome option.
Related: rhbz#663099
> Add --nohome option to autopart command.

- pykickstart/commands/raid.py
- tests/commands/raid.py
Classes RHEL7_Raid and RHEL7_RaidData should use base classes
F25_Raid and F25_RaidData, that already support the --chunksize
option.
> Add support for --chunksize option to RHEL7.

- pykickstart/commands/autopart.py
- tests/commands/autopart.py
A /home partition will not be created with --nohome option.
(cherry picked from commit b83b669)
> Add --nohome option to autopart command in RHEL7.

- docs/kickstart-docs.rst
- pykickstart/commands/autopart.py
- pykickstart/handlers/rhel7.py
- tests/commands/autopart.py
A /home partition will not be created with --nohome option.
(cherry picked from commit b83b669)
> Add --nohome option to autopart command to RHEL7.

- docs/kickstart-docs.rst
- pykickstart/commands/autopart.py
- pykickstart/handlers/f26.py
- tests/commands/autopart.py
Added new options to autopart command in Fedora 26:
A /home partition will not be created with --nohome option.
A /boot partition will not be created with --noboot option.
A swap partition will not be created with --noswap option.
> Add --nohome, --noboot and --noswap options to autopart command.

- tests/commands/realm.py
Realm command requires to have the domain as the last parameter.
> Add realm command test

- pykickstart/commands/bootloader.py
Documentation about the difference between `--disabled` and `--location=none` according to https://bugzilla.redhat.com/show_bug.cgi?id=1222132#c2 and https://bugzilla.redhat.com/show_bug.cgi?id=1074522
> More documentation for bypassing the bootloader

- pykickstart/commands/repo.py
The Repo --name kickstart option is actually the Yum RepoId and not the Yum name. 
This has been the source of lot of confusion: https://bugzilla.redhat.com/show_bug.cgi?id=885151 and https://bugs.centos.org/view.php?id=7609
> Mention that repo name must not contain spaces

- pykickstart/commands/network.py
- pykickstart/constants.py
- tests/commands/network.py
By default ifcfgs/connections are bound to device name in anaconda (DEVICE).
This option allows to bind to mac address (HWADDR).
Related: rhbz#1328576
> network: add network --bindto option

- pykickstart.spec
Changes to rename `python-pykickstart` to `python2-pykickstart` by Zbigniew Jędrzejewski-Szmek.
> Backport spec file changes from downstream

- pykickstart/commands/reqpart.py
`Gettext` can sometimes return bytes which needs to be converted and this is handled in the `i18n.py` source file.
This should fix broken Rawhide builds.
> Call the _ method from i18n.py

- pykickstart/options.py
- tests/baseclass.py
- tests/pylint/runpylint.py
* Ignore a false positive 'self.handler is not callable' in tests.
* Ignore that parameters differ from overridden 'parse_args' method.
> Pylint fixes

- pykickstart/commands/autopart.py
It should be the F20_Autopart version from which new versions of
the class used in Fedora 20+ and RHEL 7 inherit, not the archaic
RHEL6 version of the class which can never meet the 'mount'
command.
> Fix which Autopart class checks for the 'mount' command

- docs/kickstart-docs.rst
- pykickstart/commands/clearpart.py
- pykickstart/handlers/__init__.py
- pykickstart/handlers/f28.py
- pykickstart/handlers/rhel7.py
- pykickstart/version.py
- tests/commands/clearpart.py
- tests/version.py
Specifying this option in a ks file will ensure that any LDL DASDs
will be (re)formatted to CDL format.
This option is already supported in RHEL7.
(cherry-picked from commit ec9e128)
> Add clearpart --cdl option

- docs/kickstart-docs.rst
- pykickstart/commands/method.py
Commands which are required for specifying base repo weren't mentioned in docs. So users can get easily confused that without these commands the closest mirror will be used.
> Commands for specifying base repo are mentioned in docs

- pykickstart/base.py
- tests/handlers.py
In the class BaseHandler, dictionaries commandUpdates and dataUpdates
were applied directly on class atrributes commandMap and dataMap
of handlers for requested versions.
> Don't modify the original command and data mappings.

- pykickstart/commands/firewall.py
- pykickstart/handlers/f28.py
- tests/commands/firewall.py
Needed for [1] where we would like to include firewalld
and configure firewalld in Atomic Host (in the ostree) and
have Anaconda leave the delivered "defaults" in place.
[1] https://pagure.io/atomic-wg/issue/401
> master: firewall: add --use-system-defaults arg to command

- pykickstart/commands/firewall.py
- pykickstart/handlers/f27.py
- pykickstart/handlers/f28.py
- tests/commands/firewall.py
Needed for [1] where we would like to include firewalld
and configure firewalld in Atomic Host (in the ostree) and
have Anaconda leave the delivered "defaults" in place.
[1] https://pagure.io/atomic-wg/issue/401
> pykickstart-2: firewall: add --use-system-defaults arg to command

- pykickstart/commands/firewall.py
- pykickstart/handlers/rhel7.py
Needed for [1] where we would like to include firewalld
and configure firewalld in Atomic Host (in the ostree) and
have Anaconda leave the delivered "defaults" in place.
[1] https://pagure.io/atomic-wg/issue/401
(cherry picked from commit 6c2ac9500dcfc9c32e1bd329f1a0a16e8c02043b)
> rhel7-branch: firewall: add --use-system-defaults arg to command

- Makefile
Without this you won't be able to do a build with make local because `kickstart-docs.txt` file is used to create an rpm but expected in docs folder and not in `docs/_build` folder.
> Copy txt files from _build folder on make local call

- pykickstart/commands/logging.py
- tests/commands/logging.py
Default value of the logging level should be info. Also if the logging
command is specified in the input kickstart file, we want to include
it in the output kickstart file.
Resolves: rhzb#1543194
> Logging level should be always set (#1543194)

- pykickstart/commands/__init__.py
- pykickstart/commands/authconfig.py
- pykickstart/commands/authselect.py
- pykickstart/handlers/f28.py
- tests/commands/authconfig.py
- tests/commands/authselect.py
- tests/misc.py
The authconfig program is deprecated, so the authconfig command will
use the authconfig compatibility tool and the new authselect command
will use the authselect program.
Related: rhbz#1542968
**Depends on:** https://github.com/rhinstaller/anaconda/pull/1327
> Authconfig is replaced with authselect

- pykickstart/base.py
- tests/misc.py
It wasn't possible to parse deprecated commands with data,
for example device, dmraid and multipath in Fedora 28.
Added a test that will try to parse all deprecated commands.
> Fix deprecated commands with data

- Makefile
The default timeout for nosetests was 10 seconds, but sometimes
it wasn't enough. Changed to 60 seconds.
> Change the timeout for nosetests

- pykickstart/base.py
- tests/base.py
The _sortCommand method should be part of the _setCommand method,
otherwise we might set the command without changing the _writeOrder
dictionary.
This should fix the resetCommand method, where the dictionary wasn't
updated, so the old instance of the command was used to generate the
kickstart representation.
Resolves: rhbz#1578930
> Include the _sortCommand to the _setCommand method (#1578930)

- pykickstart/commands/bootloader.py
- pykickstart/commands/partition.py
- pykickstart/handlers/rhel8.py
- tests/commands/bootloader.py
- tests/commands/deviceprobe.py
- tests/commands/ignoredisk.py
- tests/commands/install.py
- tests/commands/partition.py
- tests/commands/upgrade.py
Apply the changes in https://github.com/clumens/pykickstart/pull/217 to another handler.
> Deprecate commands and options in another handler

- pykickstart/commands/__init__.py
- pykickstart/commands/syspurpose.py
- pykickstart/handlers/rhel8.py
- tests/commands/syspurpose.py
The syspurpose ("system purpose") command makes it possible for the
user to describe how the given system is intended to be used after
the installation.
This information can then be used to properly subscribe the system
to the correct entitlements (in cases subscribing a system is possible).
Resolves: rhbz#1612061
> Add the syspurpose command (RHEL version)

- pykickstart/commands/__init__.py
- pykickstart/commands/syspurpose.py
- pykickstart/handlers/rhel8.py
- tests/commands/syspurpose.py
The syspurpose ("system purpose") command makes it possible for the
user to describe how the given system is intended to be used after
the installation.
This information can then be used to properly subscribe the system
to the correct entitlements (in cases subscribing a system is possible).
> Add the syspurpose command

- pykickstart/commands/syspurpose.py
- tests/commands/syspurpose.py
Without the trailing newline the next command will be written
on the same line, leading to ugly or even invalid kickstart file.
Related: rhbz#1612061
> Add missing trailing newline for syspurpose __str__ method

- pykickstart/commands/btrfs.py
- pykickstart/commands/logvol.py
- pykickstart/commands/mount.py
- pykickstart/commands/partition.py
- pykickstart/commands/raid.py
- pykickstart/options.py
- tests/options.py
If a mount point is specified as a path, we should normalize this path.
For example '/var/' should be normalized to '/var'.
Resolves: rhbz#1626557
> Normalize the mount point

- tests/pylint/runpylint.py
Ignore the warning from pylint 2.2.2 for unnecessary pass statement.
> Fix pylint errors

- pykickstart/options.py
- pykickstart/sections.py
- tests/commands/bootloader.py
If we try to parse a deprecated option of a kickstart command, the
option parser should issue a warning. This functionality was broken
because of kickstart sections.
Kickstart commands are defined by classes specific for the given
version. In their case, the option parser don't have to check the
defined options against the current version of the kickstart syntax.
If the option is valid, then it is defined. If the option is removed,
then it is not defined. If the option is deprecated, then it is marked
as deprecated.
Kickstart sections are defined by classes common for all versions.
In their case, the option parser was expected to check the defined
options against the current version. However, that broke the detection
of deprecated options for kickstart commands.
Since the support for …
> Fix warnings for deprecated options of kickstart commands

- pykickstart/parser.py
`collections.abc` was introduced in python 3.3. Importing these classes
from `collections` directly will be deprecated in 3.8 and already makes
the linting fail.
Note: we should move this into a `try` / `except ImportError` block if we care about python < 3.3. Do we?
> parser: use collections.abc to import Iterator

- pykickstart/parser.py
The `collections.abc` python module was introduced from python 3.3 but pykickstart still supports python 2 builds.
Introduced by PR https://github.com/dcantrell/pykickstart/pull/251.
@dcantrell I have found that thanks to our daily builds. You have now two options.
1) Merge this or similar patch (blue pill)
2) Drop python2 package from pykickstart (red pill)
The choice is your. Will you follow the white rabbit down to the rabbit hole?
> Fix backward compatibility for python2

- .travis.yml
At the moment 3.6 is in RHEL 8 and 3.7 in Fedora,
so I think it makes sense to run the Pykickstart
test suite on those in Travis as well.
> Test on recent Python versions on Travis

- pykickstart/commands/sshkey.py
At the moment we differentiate required and optional options via their
argparse docstring.
So mark the --username option of the sshkey command as
required via its docstring, so that this is properly reflected
in the online documentation on Read the Docs.
> Mark the sshkey --username option as required in docs

- pykickstart/parser.py
- pykickstart/sections.py
The ``%packages --default`` will now force default environment. User can't change the environment even when he thinks he did. As a bonus Anaconda will use the user-set environment everywhere but not for installation.
All groups and packages written in the ``%packages`` section are installed correctly but they are not propagated to the output kickstart file.
In this commit I'm changing the output section generator to print all the groups and packages to the output kickstart but avoiding environment, which will be forced and can't be changed. Anaconda may change this behavior in the future but in that case the `--default` is not used and will be disabled.
Also change documentation to mention that only environment is set nothing else.
> Make %packages --default attribute sane

- Makefile
- pykickstart.spec.in
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>
This pull request is to follow up #259 .
The upstream repository contains temporary `pykickstart.spec.in` the file which is generated by Makefile `make pykickstart.spec`
> Add pykickstart.spec.in for packit

- packit.yaml
We are working on a next release of packit where we'll finally implement jobs.
Our current plan is to change the schema, which means that future version of
packit would fail parsing this config file.
This PR therefore removes content from packit.yml which packit does not even
process now.
> packit.yml: remove unused content

- docs/gen_commands_docs
- docs/gen_sections_docs
- pykickstart/commands/bootloader.py
Specify when the installer adds the bootloader options `rhgb quiet`
and how they can be disabled.
We need to prepend a path to the local repository to `sys.path`,
so the documentation for kickstart commands and handlers can be
generated from the source files in the repository instead of
files of the installed pykickstart package.
> Fix the documentation of bootloader --append

- pykickstart/sections.py
Drop the reference to "first CD-ROM" and "installation media"
instead and also note comps files might be found in the network
installation repos as well.
Also note that --ignoremissing should work for module streams as well.
> A couple fixes for %packaging section docs

- tests/tools/ksflatten.py
The expected failure will only happen for non-root users.
> Skip FailsToOpenOutputFile_TestCase if running as root

- pykickstart/commands/repo.py
- pykickstart/commands/url.py
Tell users that the ssl parameters should not be used and there is preparation for a replacement.
This is a replacement PR for https://github.com/pykickstart/pykickstart/pull/277 .
> Add note for the repo and url ssl options

- docs/versionremoved.py
Sphinx v2.0.0 added a new mapping, optionally import it and set the
versionremoved value.
This also returns parallel read/write safe set to True.
Closes #286
> Update versionremoved sphinx extension

- Makefile
Makefile should not check specific package because the package name can change and it also changed.
Zanata client is named now `python3-zanata-client` and not `zanata-python-client` as was in Makefile.
> Fix check for python zanata client in Makefile

- pykickstart.spec.in
Right now on Rawhide (F32) pykickstart can't be build because
python2-ordered-set and python2-requests do not exists anymore.
The best approach seems to me to drop python2 compatibility and support
pykickstart only as python3 from now on.
---------------------
I don't insist on this solution but it would be great to make the spec file in the upstream working. What do you think @bcl ?
> Drop python2 compatibility

- pykickstart/commands/__init__.py
- pykickstart/commands/rhsm.py
- pykickstart/handlers/rhel8.py
- tests/commands/rhsm.py
Add a new command called "rhsm", that makes it possible to specify
Red Hat subscription related data, used to subscribe a system during
a kickstart based installation and to enable subscription related services.
Options at a glance:
--organization & --activation-key (can be passed more than once)
Organization id and at least once activation key are required.
--connect-to-insights
Connects the target system to Red Hat Insights.
--proxy
Configures RHSM to use a HTTP proxy, syntax is the same as for
other --proxy options for other commands, such as the repo command.
--server-hostname
Sets custom Candlepin instance URL.
--rhsm-baseurl
Set custom content base URL.
Related: rhbz#1748281
> Add the rhsm command

- pykickstart/commands/timezone.py
- pykickstart/handlers/f32.py
- pykickstart/parser.py
- pykickstart/sections.py
- tests/args_names.py
- tests/commands/timezone.py
- tests/packages.py
The majority of Kickstart options use lowercase hyphenated naming scheme. This adds the `--exclude-weakdeps` alias for `--excludeWeakdeps` and `--inst-langs` for `--instLangs`, which moves Kickstart a bit closer to consistency.
> Add lowercase aliases for camelCased %packages options

- pykickstart/commands/driverdisk.py
It can be specified by LABEL and UUID too.
> Add missing information for driverdisk KS command

- pykickstart/commands/url.py
URL command have still it's meaning. Not sure why this part of the documentation was added but `mirrorlist` does not replacing url.
Mirrorlist should be used for mirrorlist server, however, url should be used to point directly to the server repository.
> Remove url command doc that it's replaced

- pykickstart/commands/url.py
Documentation for --url duplicating between version. Let's take another approach and tell there what changed instead of what it is doing on version update.
Update to fix problems of https://github.com/pykickstart/pykickstart/pull/309.
> Make --url doctext more understandable

- pykickstart/commands/repo.py
- pykickstart/handlers/f33.py
- pykickstart/version.py
- tests/commands/repo.py
- tests/version.py
The ``repo --ignoregroups`` parameter is not used by Anaconda from yum -> dnf transition. I don't think we want to add it back but instead we can remove this from our API.
P.S.: Not sure if the deprecation is done correctly. Could you please verify that before merge @bcl.
> Deprecate repo ignoregroups

- Makefile
- docs/programmers-guide
- pykickstart/commands/network.py
- pykickstart/options.py
This was being pulled from the Fedora wiki, but has remained unchanged
since it was first posted. pykickstart docs are now separate from Fedora
so it is easier to maintain this here in the repo.
This also removes the need for network access while building, which is
usually not available.
> docs: Maintain programmers-guide in the repo

- .travis.yml
Adding this check so devs can know in advance of a future Python release that `pykickstart` still works. This is more important now that Python has increased the release cycle. The test is allowed to fail.
> Add Travis test for Python nightly

- pykickstart/commands/harddrive.py
- pykickstart/handlers/f33.py
- tests/commands/harddrive.py
It's not supported by Anaconda for a long time. All the Anaconda code was using `biospart` attribute was that it's not yet supported and this code was in Anaconda from 2012. Let's remove this completely and make everything simpler.
See https://github.com/rhinstaller/anaconda/pull/2810
-------------------------
Is there a way how to avoid changing old test case when removing arguments? Did I missed something?
> Remove harddrive --biospart support

- setup.py
The switch to setuptools dropped this, breaking script installation.
> setup.py: Fix script installation without filename extension

- pykickstart/parser.py
- tools/ksvalidator.py
* mkdtemp and mkstemp will determine tmp dir based on runtime OS
I haven't modified tests since there are so many failures on windows (of 486 tests 61 failed, 16 had errors) but they should pass on *nix since [`/tmp` is the first default lookup.](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir)
> Make tmp file creation cross-platform in ksvalidator to support Windows

- pykickstart/commands/autostep.py
- pykickstart/handlers/f34.py
- tests/commands/autostep.py
It doesn't really work in Anaconda anymore.
> Deprecate the autostep command

- tests/misc.py
It's normal to deprecate commands before removing, so usually the final version of a command will be a subclass of *both* `DeprecatedCommand` and `RemovedCommand`.
This failed for me in #364. I think all subsequent `RemovedCommand` usages depend on this.
> Fix deprecation test for removed commands

- tests/misc.py
Make sure that deprecated kickstart commands issue the expected warnings.
> Check warnings of the deprecated kickstart commands

- pykickstart/commands/bootloader.py
- pykickstart/commands/interactive.py
- pykickstart/commands/langsupport.py
- pykickstart/commands/lilocheck.py
- pykickstart/commands/monitor.py
- pykickstart/commands/mouse.py
- pykickstart/commands/upgrade.py
- pykickstart/handlers/f18.py
- pykickstart/handlers/f29.py
- pykickstart/handlers/f7.py
- pykickstart/handlers/fc4.py
- tests/commands/bootloader.py
- tests/commands/interactive.py
- tests/commands/langsupport.py
- tests/commands/lilocheck.py
- tests/commands/monitor.py
- tests/commands/mouse.py
- tests/commands/upgrade.py
- tools/ksverdiff.py
This should make all removals conform to The New Way™.
Most of this is straightforward, but the lilo-related commits needed making choices about how to classify deprecated/removed.
> Change old command removals to use RemovedCommand

- pykickstart.spec.in
They aren't needed for the build unless runtests has been selected (it
is disabled by default).
Resolves: rhbz#1916735
> Conditionally BuildRequire coverage and sphinx for runtests

- pykickstart.spec.in
- pykickstart/base.py
- pykickstart/commands/rootpw.py
- pykickstart/commands/user.py
- pykickstart/i18n.py
- pykickstart/load.py
- pykickstart/parser.py
- setup.py
- tests/baseclass.py
- tests/commands/logvol.py
- tests/handle_unicode.py
- tests/include.py
- tests/load.py
- tests/preprocess.py
- tests/version.py
- tools/ksshell.py
This was necessary when transitioning from Python 2 to 3, but now that
pykickstart is Python 3 only it is just extra code that is unneeded.
> Remove python six library

- tests/base.py
- tests/commands/__init__.py
When testing an installed package instead of the source tree the test
needs to examine the installed source path, not the path relative to the
test.
Related: rhbz#1968762
> tests: Use pykickstart/commands relative to the import

- pykickstart/commands/autopart.py
- pykickstart/commands/bootloader.py
- pykickstart/commands/btrfs.py
- pykickstart/commands/fcoe.py
- pykickstart/commands/logvol.py
- pykickstart/commands/ostreesetup.py
- pykickstart/commands/partition.py
- pykickstart/commands/raid.py
- pykickstart/commands/volgroup.py
- pykickstart/handlers/rhel9.py
- pykickstart/version.py
- tests/commands/partition.py
- tests/version.py
Add handler for RHEL 9, so that RHEL only commands and RHEL command
variations can be used in Anaconda on RHEL 9.
The RHEL 8 version of the handler was created by commits:
16ff122476ba01874a154b7e45204b8a71e6cdf5
b13b5a1e512c0705aa295c29526e8615da6e6296
Resolves: rhbz#1966730
> Add RHEL 9 handler

- pykickstart/commands/autopart.py
- pykickstart/commands/bootloader.py
- pykickstart/commands/btrfs.py
- pykickstart/commands/fcoe.py
- pykickstart/commands/logvol.py
- pykickstart/commands/ostreesetup.py
- pykickstart/commands/partition.py
- pykickstart/commands/raid.py
- pykickstart/commands/volgroup.py
- pykickstart/handlers/rhel9.py
- pykickstart/version.py
- tests/commands/partition.py
- tests/version.py
The first commit handles some BTRFS-removal related tasks to keep BTRFS support removed also in RHEL 9.
The second commit does RHEL specific command version bumps.
The third commit adds the actual RHEL 9 handler.
PR for Anaconda to use the RHEL 9 handler: https://github.com/rhinstaller/anaconda/pull/3424
> Backport the RHEL 9 handler to the RHEL 9 branch

- pykickstart/base.py
Explicitly return `None` from the `parse` method of the `DeprecatedCommand` class.
Otherwise, Pylint might detect the `assignment-from-no-return` error.
> The parse method is expected to return a value

- pykickstart/commands/authconfig.py
- pykickstart/handlers/f35.py
- tests/commands/authconfig.py
Authconfig compatibility tool (from authselect-compat) will be removed from Fedora 35:
https://fedoraproject.org/wiki/Changes/RemoveAuthselectCompatPackage
> remove authconfig support

- pykickstart/sections.py
The next section describes `%pre-install` and refers to it as "pre-install" script, so this is confusing, possibly even misleading.
**warning** I'm sneaking in also a typo fix in a separate commit :)
> Be more consistent when referring to `%pre`

- pykickstart/parser.py
- tests/preprocess.py
- tools/ksvalidator.py
Previously an empty file would return a confusing error. This fixes it
by checking the preprocess call for None, and by running strip on the
file before checking if it is empty. Also includes tests.
Fixes #388
> ksvalidator: Handle empty files

- pykickstart/commands/bootloader.py
This fixes #139 by changing the help string to describe what actually
changed (we cannot set it to an empty string) and metavar is overridden
so the _ doesn't show up in the docs.
> bootloader: Fix --md5pass documentation

- pykickstart/sections.py
- tests/tools/ksvalidator.py
- tools/ksvalidator.py
In Fedora 32 we added the lower-case versions of --instLangs and
--excludeWeakdeps by extending the current entries. This causes problems
when trying to use ksvalidate. It would not fail if --inst-langs was
passed to RHEL8 for example.
Fixes #395
> Fix validation of packages arguments

- pykickstart/sections.py
- pykickstart/version.py
- tests/packages.py
- tests/version.py
The `%packages --ignorebroken` feature is not supported on RHEL. Handle
this use case in pykickstart, so we don't have to deal with it in anaconda.
Tested on F37 and RHEL9.
> Remove the --ignorebroken option from RHEL handlers

- docs/gen_sections_docs
- pykickstart/sections.py
- pykickstart/version.py
- tests/packages.py
- tests/tools/ksshell.py
- tests/version.py
- tools/ksflatten.py
- tools/ksshell.py
- tools/ksvalidator.py
This is the backport of pr #403 with additional changes fixing how RHEL9 selects the default pykickstart version to use.
> Backport dropping --ignorebroken

- pykickstart/i18n.py
Previously it was changing the global gettext domain which could cause
problems for other applications. This updates it to pass the domain to
every call, and also switches to using the more robust .translation()
method as used by Anaconda.
Fixes #405
> i18n: Pass gettext domain on every translation call

- .github/workflows/tests.yml
Ends up the if statement already evaluates it as an expression so you
don't use ${{ }} for the variables.
> github: Fix workflow to only send coverage for python 3.9

- pykickstart/commands/rootpw.py
- pykickstart/handlers/f37.py
- pykickstart/handlers/rhel9.py
- tests/commands/rootpw.py
This will be used by Anaconda to allow root *password* logins via ssh.
Resolves: rhbz#2083269
> rootpw: Add an --allow-ssh argument

- pykickstart/commands/zfcp.py
- pykickstart/handlers/f37.py
- tests/commands/zfcp.py
If automatic LUN scanning is available, it is sufficient to specify
an FCP device number with `zfcp --devnum=<device_number>`.
Related: rhbz#1432883
> Add support for automatic LUN Scan

- pykickstart/base.py
- tests/base.py
When a kickstart is output the commands are grouped by write priority,
then alphabetical within the group. This isn't how it was actually
working -- it was using the full class name with release prefixes (eg.
F37_) so a newer command would sort before older commands, as seen with
the recent rootpw change.
This changes the insert to compare based on the command name portion of
the class name, without the prefix. This will change the order of some
things -- but in the future the output will be in stable alphabetical
order.
Resolves: rhbz#2096871
> Write commands in alphabetical order

- pykickstart/commands/autopart.py
- pykickstart/handlers/f38.py
- tests/commands/autopart.py
Add F38_AutoPart class with a new Kickstart flag that creates a swap partition for hibernation.
Installer implementation: https://github.com/rhinstaller/anaconda/pull/4275
> Add --hibernation option to AutoPart

- pykickstart/commands/sshkey.py
- pykickstart/handlers/f38.py
- tests/commands/sshkey.py
This allows spaces and quotes to be used in the options section of the
ssh key, eg:
sshkey --username=root "from=\"192.168.1.1\" ssh-rsa ..."
sshkey --username=user "\"/usr/bin/rrsync /home/user/public_html/\",no-port-forwarding ssh-rsa ..."
Resolves: rhbz#2117734
> sshkey: Escapes quotes in the ssh key

- pykickstart/commands/timezone.py
With reStructuredText the :: after example already start a code block.  This makes the backticks redundant and are shown in the rendered documentation.
https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#timezone
> Fix syntax of a code sample

- Makefile
The coverage report says "No data to report" after running the unit tests. It can be fixed with the removal of the `--include` option. Since the coverage is collected with the `--source=pykickstart,tools` option, there are no other data anyway.
> Fix the coverage report

- Makefile
- pykickstart.spec.in
This will allow us to do `make rc-release` and get rpm files of pykickstart. Otherwise it's pretty hard to do when you don't know the project so much.
> Improve local rpm build experience

- pykickstart/parser.py
- tests/packages.py
The %package section argument were changed in F32 to prefer the non-camelcase form. But when using an older version they should be output using the old form, not the new one.
Fixes #444
> Fix handling of package section arguments in older versions

- pykickstart/base.py
- pykickstart/commands/autopart.py
- pykickstart/commands/logvol.py
- pykickstart/commands/mount.py
- pykickstart/commands/partition.py
- pykickstart/commands/raid.py
- pykickstart/commands/reqpart.py
- pykickstart/commands/volgroup.py
- pykickstart/options.py
- tests/commands/logvol.py
- tests/commands/partition.py
- tests/commands/raid.py
- tests/commands/reqpart.py
- tests/commands/volgroup.py
Previously a command would have to implement checking the .seen attribute on commands that it conflicts with, and manually update the command description with the commands that it could not be used with.
With this change you can implement command conflict support by adding a list to the class:
conflictingCommands = ["raid", "reqpart"]
Pass this list to the command's KSOptionParser as ``conflicts``:
KSOptionParser(..., conflicts=self.conflictingCommands)
And then in the first version that the conflict occurs, call the helper function with a translated error message from the ``parse`` function:
self._checkConflictingCommands(_("The %s and autopart commands can't be used at the same time"))
the command's description will have a list of the conflicting commands appended to it automatically.
> Add conflicting commands support

- pykickstart/commands/displaymode.py
The displaymode commands (text, cmdline, graphical) control the mode during the installation, and the mode that the system will boot into by default. This updates the description to correctly reflect that behavior.
> displaymode: Update description to describe behavior

- pykickstart/commands/realm.py
The 'pipes' module was marked deprecated in Python 3.11, slated for removal in Python 3.13 [1]. The only bit of it used was `pipes.quote()`, which can be easily replaced by `shlex.quote()`, as it is also implemented in the 'pipes' module.
[1] https://peps.python.org/pep-0594/#pipes
> realm: switch from pipes.quote() to shlex.quote()

- Makefile
- pykickstart.spec.in
Fedora doesn't want to run coverage during rpm builds, so make a new target that just runs the tests and adjust the example .spec.in file accordingly.
> Makefile: Add a test-no-coverage target

- .readthedocs.yaml
This will be required after September 25, 2023
See https://blog.readthedocs.com/migrate-configuration-v2/
> rtd: Add the .readthedocs.yaml config file

- pykickstart/base.py
- pykickstart/commands/__init__.py
- pykickstart/commands/autopart.py
- pykickstart/commands/logvol.py
- pykickstart/commands/mount.py
- pykickstart/commands/ostreecontainer.py
- pykickstart/commands/ostreesetup.py
- pykickstart/commands/partition.py
- pykickstart/commands/raid.py
- pykickstart/commands/reqpart.py
- pykickstart/commands/volgroup.py
- pykickstart/handlers/rhel9.py
- pykickstart/options.py
- tests/commands/logvol.py
- tests/commands/ostreecontainer.py
- tests/commands/ostreesetup.py
- tests/commands/partition.py
- tests/commands/raid.py
- tests/commands/reqpart.py
- tests/commands/volgroup.py
- tox.ini
Also backport the conflicting commands framework.
This replaces #461
Resolves: RHEL-17662
> Backport ostreecontainer to RHEL9

- pykickstart/commands/autostep.py
- pykickstart/commands/logging.py
- pykickstart/commands/method.py
- pykickstart/commands/repo.py
- pykickstart/handlers/f40.py
- tests/baseclass.py
- tests/commands/autostep.py
- tests/commands/logging.py
- tests/commands/method.py
- tests/commands/raid.py
- tests/commands/repo.py
- tests/commands/vnc.py
Remove the following deprecated kickstart commands and options:
- `autostep`
- `method`
- `logging --level`
- `repo --ignoregroups`
Related: INSTALLER-3849
> Remove deprecated kickstart commands and options

- pykickstart/commands/timezone.py
- pykickstart/handlers/f40.py
- tests/commands/timezone.py
The future deprecation of these kickstart options was announced in Fedora 32 and
33. The support for these options will be removed from Anaconda in Fedora 40.
Related: INSTALLER-3887
> Deprecate timezone --isUtc, --ntpservers and --nontp kickstart options

- pykickstart/commands/btrfs.py
- tests/commands/btrfs.py
It was deprecated in RHEL8, time to remove it.
Resolves: RHEL-34009
> btrfs: Remove support for the btrfs command on RHEL10

- pyproject.toml
This is to make the metadata consistent with reality (the tests all pass on python 3.6)
> pykickstart is supported on python 3.6+

- pykickstart/commands/vnc.py
- pykickstart/handlers/rhel10.py
- tests/commands/vnc.py
VNC has been replaced by the Remote Desktop protocol, which is currently controlled just by the inst.rdp boot option and does not have a corresponding
kickstart command.
Resolves: RHEL-41219
> Mark the vnc command as deprecated on RHEL 10

- docs/versionremoved.py
The alias at sphinx.directives.other has been long deprecated and was finally removed.
Fixes #500
> doc/versionremoved: Update VersionChange import for Sphinx 8.0.0

- pykickstart/commands/module.py
- tests/commands/module.py
Also increase consistently with other deprecated commands, by calling the DeprecatedCommand init, instead of the custom parser.
> commands: Add missing DeprecatedCommand class to F41_Module

- pykickstart/sections.py
Add information that %onerror could be forced by inst.cmdline.
Resolves: RHEL-47142
Not 100% sure if we want to mention Anaconda kernel parameter in pykickstart documentation but I see this beneficial.
> Enhance %onerror section with recommendation

- pykickstart/commands/autopart.py
- pykickstart/commands/partition.py
- pykickstart/handlers/f41.py
- tests/commands/autopart.py
- tests/commands/partition.py
This enables support for creating LUKS HW-OPAL devices in Anaconda The feature itself is controlled by the existing "--luks-version" option, but we need the OPAL administrator passphrase from user.
> Add "opal-admin-passphrase" option for autopart and part commands

- pykickstart/base.py
- tests/base.py
Returning None can cause callers, like anaconda, to traceback when they expect to get a list. This was revealed by the deprecated module command. Also include a test for this.
> DeprecatedCommand: Return empty list for dataList

- pykickstart/options.py
In Python 3.13 and 3.12.7, the behavior of _parse_optional has changed. It used to raise an error on multiple matching actions itself, and only ever return None or an option tuple. Now the "raise error on multiple matching actions" code was moved out into consume_optional, and _parse_optional returns either None or a *list* of option tuples, which contains more than one if multiple actions match. See:
https://github.com/python/cpython/pull/124631
https://github.com/python/cpython/issues/58573
This adapts to the change in a way that should work on both older and newer Pythons. I re-implemented the handling of multiple matching options so we don't have to worry about licensing and attribution if we copied in upstream's version.
> options: adjust to behavior change in upstream _parse_optional

- .github/workflows/tests.yml
- pykickstart/commands/module.py
- tox.ini
Also drop pin of pycodestyle.
pykickstart uses a private argparse function, _parse_optional, which recently changed behavior in python 3.12.7 so switch to using that version in the workflow.
> tox: Add py313 to tox and 3.12.7 to workflow

- .github/workflows/rhel-7.yml
- .github/workflows/rhel-8.yml
- tests/pylint/runpylint.py
- tox.ini
Based on the branch name, only run a subset of the python versions. rhel7-branch uses python 3.6
rhel8-branch uses python 3.8
Run the other tests on master and on rhel9-branch and rhel10-branch.
This will allow use of python 3.9 specific features.
> tests: Limit the python versions used in testing

- .github/workflows/rhel-7.yml
- .github/workflows/rhel-8.yml
- .github/workflows/tests.yml
Version 20.04 will not be supported after 4/1/2025, switch to -latest so that it will hopefully not need changes every time a release is removed.
> workflows: Switch to ubuntu-latest

- pykickstart/commands/raid.py
- pykickstart/handlers/f43.py
- tests/commands/raid.py
This used to be done when MD names were based on minor to remove the prefix from names such as "md0". This is no longer true and parsing the name in this way was removed in Fedora 19 (see d55f1adba0bdf73fc41d88e0632dfb0dbf418e8e). Removing the prefix from the name now causes issue when users use names like for example "md_xyz" and then try to use the name to refer to the new array by name in other commands like volgroup.
> Do not remove "md" prefix from RAID names

- pykickstart/commands/clearpart.py
GPT was made default for x86_64 architecture in Fedora 37.
> Update documentation for clearpart --initlabel option.

- pykickstart/commands/__init__.py
- pykickstart/commands/bootc.py
- pykickstart/commands/ostreecontainer.py
- pykickstart/commands/ostreesetup.py
- pykickstart/handlers/f43.py
- tests/commands/bootc.py
- tests/commands/ostreecontainer.py
- tests/commands/ostreesetup.py
Bootc container becomes a new way of OS install supported by the Anaconda. This requires introduction of new kickstart command to support it.
Related discussion: https://github.com/rhinstaller/anaconda/discussions/5197
Resolves: INSTALLER-4024
This is the base for the following change in Anaconda: https://github.com/rhinstaller/anaconda/pull/6298
> Add support for new bootc kickstart command

- docs/kickstart-docs.rst
When a new section is added, like %certificate, the chapter numbering that comes after it needs to be incremented to account for the auto-numbering of the sections documentation.
> docs: Fix chapter numbering after adding certificate

- pykickstart/commands/__init__.py
- pykickstart/commands/rdp.py
- pykickstart/handlers/f43.py
- tests/commands/rdp.py
We removed VNC support recently and replaced that with RDP. We missed the kickstart support for RDP before so now let's fix it and add it back based on the feedback we have got.
> Add support for RDP

- pykickstart.spec.in
python3-build is not available in the RHEL buildroot and is used only for make targets which are not used when building the package.
> spec: drop python3-build dependency
