pykickstart/pykickstart

Makefile
docs/kickstart_docs.rst
pykickstart.spec

A piece of "Friday work". Basically I ran pandoc on our Anaconda/Kickstart wiki, editted the result to resolve some minor issues and saved the final result as docs/kickstart_docs.rst. You can check how the docs look like by visitting the file in github's web and letting it render it for you nicely [1]. In order to review, I think the best input should be a diff between what I got from pandoc (should be the same as on the wiki) and the result [2]. See the commit message for a rationale behind this.
[1] https://github.com/vpodzime/pykickstart/blob/master-docs/docs/kickstart_docs.rst
[2] https://vpodzime.fedorapeople.org/pandoc_edited.diff

Who let the docs out?!

---

Makefile

This is a simple dependency check.

Check if python-nose is installed and abort with error if not

---

tests/README.rst

Makes it easier to understand how tests are executed and organized.

Add test documentation

---

tests/version.py

1) Improve test coverage
2) The new test at line 215 actually revealed a bug, the local variable found wasn't defined and in case of error the finally block raised an exception.

Improve test coverage for version.py

---

.gitignore
Makefile

and some minor fixes. Also I'd like to have .coverage and coverage-report.log uploaded in Jenkins.

Produce coverage-report.log for CI

---

tests/commands/bootloader.py
tests/commands/btrfs.py
tests/commands/device.py
tests/commands/displaymode.py
tests/commands/firstboot.py
tests/commands/group.py
tests/commands/ignoredisk.py
tests/commands/interactive.py
tests/commands/key.py
tests/commands/keyboard.py
tests/commands/lang.py
tests/commands/langsupport.py
tests/commands/lilocheck.py
tests/commands/logging.py
tests/commands/mouse.py
tests/commands/selinux.py
tests/commands/sshkey.py
tests/commands/sshpw.py
tests/commands/timezone.py
tests/commands/unsupported_hardware.py
tests/commands/url.py
tests/commands/user.py
tests/commands/volgroup.py
tests/orderedset.py

More coming along, do you want them all in one commit or split by command ?

Add more unit tests

---

tests/commands/driverdisk.py
tests/commands/iscsi.py
tests/commands/ostreesetup.py
tests/commands/partition.py
tests/commands/raid.py
tests/commands/repo.py

More tests for driverdisk, iscsi, ostreesetup, partition, raid and repo

---

Makefile

Attempt to fetch po files before running make check, and update the .pot
file before running tests against it.

Try harder to test translations.

---

tests/commands/method.py

`__getattr__` and `__setattr__` methods are now mostly covered

Improved method.py test coverage

---

docs/kickstart-docs.rst

Change network example to working one

---

docs/kickstart-docs.rst

so, it doesn't correctly highlighted

fix formating

---

Makefile

Remove the po-empty target, since it's not necessary. If no translations
are present, none will be used, and the list of languages it read in
zanata.xml no longer exists.
Keep po-fallback as a non-failing po-pull target, but stop running it
before running the tests.

Download translations less frequently.

---

docs/kickstart-docs.rst

Update documentation of network command.

Master update network command documentation

---

pykickstart/commands/device.py
pykickstart/commands/logging.py
tests/commands/firewall.py
tests/commands/group.py
tests/commands/harddrive.py
tests/commands/logging.py
tests/commands/nfs.py

Adding some more tests to help increase coverage as well as kill some mutants.

Add more tests

---

pykickstart/commands/autopart.py
pykickstart/commands/raid.py
pykickstart/commands/sshkey.py
pykickstart/commands/timezone.py
pykickstart/commands/upgrade.py
pykickstart/handlers/f23.py
pykickstart/handlers/f24.py
pykickstart/handlers/f25.py
tests/commands/autopart.py
tests/commands/group.py
tests/commands/harddrive.py
tests/commands/nfs.py
tests/commands/raid.py
tests/commands/rootpw.py
tests/commands/sshkey.py
tests/commands/sshpw.py
tests/commands/timezone.py
tests/commands/upgrade.py
tests/commands/url.py
tests/commands/volgroup.py
tests/commands/zfcp.py

Additional test coverage and refactoring. Also fixes #112

More test coverage

---

pykickstart/commands/network.py

Apply the changes done in 24f92ccbd6b7c8ac73ff2569c23c273364c7f55a
to the right place.

Update network command documentation also in option help strings.

---

README
README.rst
pykickstart.spec

Add build instructions for the kickstart documentation.
Also turn the README file to rst when we are at it.

Add build insturctions for the docs

---

pykickstart/commands/autopart.py
pykickstart/commands/autostep.py
pykickstart/commands/keyboard.py
pykickstart/commands/lang.py
pykickstart/commands/logvol.py
pykickstart/commands/monitor.py
pykickstart/commands/nfs.py
pykickstart/commands/partition.py
pykickstart/commands/services.py

Fix markup a bit in arguments and path used in descriptions

fix markup a bit (add ``)

---

pykickstart/parser.py

Fixing bug from commit 2d6d773.

Fix python2 compatibility when printing to stderr

---

docs/kickstart-docs.rst
pykickstart/commands/raid.py
tests/commands/raid.py

(cherry picked from commit 14854a1)
Related: rhbz#1332316

Add --chunksize option to raid command.

---

docs/kickstart-docs.rst
pykickstart/constants.py
pykickstart/parser.py
pykickstart/sections.py
tests/packages.py
tests/parser/include.py
tests/script.py

Added a new section with a corresponding documentation and tests.
(cherry picked from commit a21aafc)
(cherry picked from commit 1043e9d)
(cherry picked from commit a9bec82)
Related: rhbz#1412538

Add an %onerror script section.

---

Makefile
pykickstart/commands/snapshot.py

1. Fix documentation issue. 
*Because of this the documentation wasn't generated.*
2. Add generation of documentation to ci 
*To prevent `1.`*
3. Fix snapshot command error.
*Sorry for that, my mistake.*

Fix snapshot command

---

docs/kickstart-docs.rst
pykickstart/commands/__init__.py
pykickstart/commands/installclass.py
pykickstart/handlers/f26.py
tests/commands/installclass.py

Added new installclass command with --name option.

Add new installclass command.

---

pykickstart/commands/__init__.py
pykickstart/commands/installclass.py
pykickstart/handlers/f26.py
tests/commands/installclass.py
tests/misc.py

Added new installclass command with --name option.

Add new installclass command in master

---

pykickstart/commands/method.py
tests/commands/method.py

The internal implementation of the method command was rewritten and
simplified. New implementation solves the problems described below
and allows easier adding of new installation methods. To ensure, that
the code works the expected way, it is fully covered by tests in the
following commit.
What was wrong?
* It wasn't possible to switch the method to 'liveimg'.
```
method.method = "cdrom"
method.method = "liveimg"
assertEqual(method.method, "liveimg") # Fails
```
* It was possible to set nonexistent attributes.
```
method.method = "cdrom"
method.nonexistent = 123 # Should raise an exception.
```
* Line `return object.__getattribute__(...)` was never executed.
Method `__getattr__` is called when an attribute lookup has not found 
the attribute in the usual places. One of these places is …

Rewrite the method command

---

docs/kickstart-docs.rst
pykickstart/parser.py
pykickstart/sections.py
tests/packages.py

Add options --timeout= and --retries= to %packages section.
Resolves: rhbz#1482912

Add timeout and retries options to %packages section (#1482912)

---

pykickstart/parser.py
pykickstart/sections.py
tests/packages.py

Add options --timeout= and --retries= to %packages section.
(cherry picked from commit a312f0b)

Add timeout and retries options to %packages section in RHEL7

---

pykickstart/commands/mount.py

Fix import in the mount command

---

pykickstart/base.py
tests/base.py

In anaconda, we need a kickstart handler, that doesn't handle any
commands and sections by default. It also shouldn't generate any
output by default. The `KickstartHandler` class is a base class of
the `BaseHandler` class that just offers the basic functionality.
Problems with the `BaseHandler`:
* it contains packages, scripts and _null_section_strings attributes
* the `_registerCommands` method cannot register empty mappings
* method `_str_` always puts the version to the output

Add the KickstartHandler class

---

Makefile
docs/conf.py
setup.py

I was working against my fork of pykickstart and not the main repo.  So merge this PR and then I'll do 3.14 to fix my mistake.  Fuck.

Well I goofed

---

Makefile
po/Makefile

Release process clean up stuff

---

.travis.yml
pykickstart/commands/method.py
tests/commands/module.py
tests/pylint/runpylint.py

Fixed errors and warnings found by pylint.

Fix pylint errors

---

pykickstart/sections.py

Describe how to install module streams & profiles, including
which combinations are valid and which not.
The group/module priority is also defined for ambiguous
cases (module wins).

Document module stream installation

---

pykickstart/commands/ignoredisk.py

The option was deprecated by
commit 67bde6b1bfe0a20d17a95620d56df96dfc805efej
but we don't want to abort the installation for existing kickstarts using the
option so loose the guard in parse method and add a deprecation warning.
If there is the --interactive option only, just issue the warning, do not raise
parse error. (These kickstarts used to be accepted.)
If there is also other option present in the command, modify the message of
raised exception with information that the --interactive option is no longer
supported. (These kickstarts used to raise the exception but the message should
be changed.)
Resolves: rhbz#1637872

Do not throw exception on deprecated ignoredisk --interactive

---

pykickstart/commands/snapshot.py

The snapshot origin was missed in the documentation which was done mostly thanks to the bad parsing.

Fix snapshot documentation

---

packit.yaml

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>
This PR adds support for packit https://github.com/packit-service/packit, which syncs upstream changes into downstream automatically. See docu on packit side https://github.com/packit-service/packit/blob/master/README.md.

Configuration file .packit.yaml

---

pykickstart/commands/repo.py

Fix the documentation based on a discussion with the DNF team about
what these options actually do with the current DNF stack.

Fix documentation for the --excludepkgs and --includepkgs repo options

---

pykickstart/commands/dmraid.py
pykickstart/commands/driverdisk.py
pykickstart/commands/firewall.py
pykickstart/commands/key.py
pykickstart/commands/network.py
pykickstart/commands/partition.py
pykickstart/commands/xconfig.py
tests/commands/__init__.py
tests/include.py
tests/newsection.py
tests/tools/ksflatten.py

This cleans up the test output so there are no extra artifacts in the output.
It also fixes the help/description test and turns it back on.

Clean up the tests

---

Makefile

This will use the git user configuration if available, or the user's
default gpg key and email address. To select a different gpg key set it
in the repo using the git config command:
git config user.signingkey 01234567890ABCDEF

gpg sign the git tag

---

Makefile

This uses the git user.signingkey to select the right gpg key to use for
the signature (the same one used for the signed git tag).

Makefile: Add creating the detached signature to the release make target

---

pykickstart/handlers/f34.py
pykickstart/version.py
tests/pylint/runpylint.py
tests/version.py

Add Fedora 34 support

---

tests/tools/ksshell.py
tools/ksshell.py

This fixes the traceback with ksshell and adds a simple test to make
sure it is minimally functional.
Resolves: rhbz#1878242

ksshell: Fix traceback and add tests

---

pykickstart/sections.py

Thanks in advance for reviewing.

Add missing spaces into the message

---

pykickstart/commands/bootloader.py
pykickstart/handlers/f34.py
tests/commands/bootloader.py

It has been deprecated since F29.

Remove the bootloader option --upgrade

---

pykickstart/commands/method.py
pykickstart/handlers/f34.py
tests/commands/method.py

Another no longer used command.

Deprecate the method command

---

pykickstart/commands/multipath.py
pykickstart/handlers/f34.py
tests/commands/multipath.py

Remove the multipath command

---

pykickstart/commands/dmraid.py
pykickstart/handlers/f34.py
tests/commands/dmraid.py

Deprecated since F24
edit: Blocked by #366

Remove the dmraid command

---

pykickstart/commands/device.py
pykickstart/handlers/f34.py
tests/commands/device.py

Deprecated since F24
edit: Blocked by #366

Remove the device command

---

pykickstart/commands/install.py
pykickstart/handlers/f34.py
tests/commands/install.py

~~At the moment still blocked by deployment of Beaker 28.1. See #347 for more details.~~

Remove the install command

---

pykickstart/commands/autostep.py
pykickstart/handlers/rhel8.py
tests/commands/autostep.py

It doesn't really work anymore.

Deprecate autostep in RHEL8

---

docs/ksvalidator.1
pykickstart/load.py
tests/tools/ksvalidator.py
tools/ksvalidator.py

A try at #382 - multiple files and globbing. Thus far, it's a quick hack to see if it's even possible.
Unfortunately there's something mysterious about the way warnings are handled, I can't divert them no matter what. Neither wrapping in `catch_warnings` nor replacing `showwarning` does anything.
This is only a draft, so no tests.

ksvalidator - multiple files

---

pykickstart/handlers/f36.py
pykickstart/version.py
tests/version.py

Add Fedora 36 support

---

pykickstart/handlers/f37.py
pykickstart/version.py
tests/version.py

Add Fedora 37 support

---

pykickstart/handlers/f38.py
pykickstart/version.py
tests/version.py

Add Fedora 38 support

---

pykickstart/sections.py

Use the example from Anaconda's docs, and point to them.
Fixes #429

Update %post example for DNS problems

---

tox.ini

whitelist_externals has changed to allowlist_externals

---

pykickstart/handlers/f39.py
pykickstart/version.py
tests/version.py

Not sure what to write here :)

Add support for Fedora 39

---

pykickstart/commands/user.py

Introduce a better option but keep a fixed version of the old code example for older distributions Fixes #451

Fix issues how to generate encrypted passwords

---

pykickstart/sections.py
tests/packages.py

The future deprecation of these kickstart options was announced in Fedora 32. The support for these options will be removed from Anaconda in Fedora 40.
Resolves: INSTALLER-3888

Deprecate %packages --instLangs and --excludeWeakdeps kickstart options

---

pykickstart/commands/network.py
pykickstart/handlers/rhel10.py
tests/commands/network.py

Deprecate network team options on RHEL 10

---

docs/gen_sections_docs
pykickstart/version.py
tests/tools/ksshell.py
tests/version.py
tools/ksflatten.py
tools/ksshell.py
tools/ksvalidator.py

Switch DEFAULT_VERSION to RHEL10 

---

pykickstart/commands/module.py
pykickstart/handlers/rhel10.py
tests/commands/module.py

Deprecate modularity on RHEL 10

---

pykickstart/commands/nvdimm.py
pykickstart/commands/timezone.py
pykickstart/handlers/rhel10.py
pykickstart/sections.py
tests/commands/nvdimm.py
tests/commands/timezone.py
tests/packages.py

~~Still a work in progress...~~ Ready for review.

Remove deprecated commands on RHEL10

---

pykickstart/options.py

Whoops. Don't know how this slipped through testing.

Fix the fix for _parse_optional changing

---

docs/kickstart-docs.rst
pykickstart/base.py
pykickstart/parser.py
pykickstart/sections.py
tests/certificate.py

This is slightly updated https://github.com/pykickstart/pykickstart/pull/514.
The modifications should be clear from the commits, especially it renames the options based on review in the https://github.com/pykickstart/pykickstart/pull/514#pullrequestreview-2478460112
https://issues.redhat.com/browse/INSTALLER-4029

%certificates section support

---

docs/kickstart-docs.rst
pykickstart/base.py
pykickstart/parser.py
pykickstart/sections.py
tests/certificate.py

Port of https://github.com/pykickstart/pykickstart/pull/517

Add support for inline certificates with `%certificate` section

---

docs/kickstart-docs.rst
pykickstart/base.py
pykickstart/parser.py
pykickstart/sections.py
tests/certificate.py

Port of https://github.com/pykickstart/pykickstart/pull/517

Edns certificates import r9

---

pykickstart/sections.py
tests/certificate.py

Make %certificate section option --dir mandatory.

---

pykickstart/sections.py

Related: RHEL-61435
Upstream PR: https://github.com/pykickstart/pykickstart/pull/526

Update %certificate section documentation

---

.github/workflows/tests.yml
Makefile
pykickstart.spec.in
pyproject.toml
requirements.txt
tests/pylint/runpylint.py

Don't run setup.py from Makefile
